Repository FESI-10th-team6/moizayo, pull requests merged in 2025-08, with the labels that each got.

#114 Feat #113 signin error message
  src/features/signin/ui/SigninForm.tsx
  src/messages/en.json
  src/messages/ko.json
  src/shared/ui/input/Input.tsx
Labels: ✨ feature

#115 Feat/#112 detail error and auth
  src/app/[locale]/gathering/[id]/page.tsx
  src/entities/gathering-detail/api/queries.ts
  src/entities/gathering-detail/model/calculateGatheringRole.ts
  src/entities/gathering-detail/model/types.ts
  src/entities/gathering-detail/ui/GatheringDetailLayout.tsx
  src/messages/en.json
  src/messages/ko.json
  src/shared/api/httpClient.ts
  src/shared/lib/date/formatDateAndTime.ts
Labels: ✨ feature

#117 Chore/#110 sentry
  instrumentation-client.ts
  instrumentation.ts
  next.config.ts
  package.json
  pnpm-lock.yaml
  src/app/api/auth/[...nextauth]/route.ts
  src/entities/gathering-detail/ui/GatheringDetailLayout.tsx
  src/entities/user/api/queries.ts
  src/entities/user/model/schema.ts
  src/entities/user/ui/ProfileEditForm.tsx
  src/features/gathering/ui/CreateGatheringForm.tsx
  src/messages/en.json
  src/messages/ko.json
  src/shared/api/httpClient.ts
  src/shared/lib/sentry/tracking.ts
Labels: 🎸 chore

#124 Refactor/#122 detail uiux
  src/app/[locale]/gathering/[id]/page.tsx
  src/entities/gathering-detail/ui/GatheringDetailLayout.tsx
  src/entities/gathering-detail/ui/GatheringDetailSkeleton.tsx
  src/entities/gathering-detail/ui/ReviewList.tsx
  src/messages/en.json
  src/messages/ko.json
  src/shared/ui/skeleton/Skeleton.tsx
  src/shared/ui/skeleton/index.ts
  src/widgets/BottomFloatingBar/BottomFloatingBar.tsx
Labels: 🛠️ refactor

#126 fix: (Signin)회원가입후 로그인시 경로 수정
  src/features/signin/ui/SigninForm.tsx
Labels: 🐞 fix

#129 Refactor/#125 gathering list a11y
  jest.config.mjs
  src/features/gathering/ui/CreateGatheringButton.tsx
  src/features/gathering/ui/GatheringLikeButton.tsx
  src/messages/en.json
  src/messages/ko.json
  src/shared/ui/dropdown/DropdownItem.tsx
  src/shared/ui/dropdown/DropdownList.tsx
  src/shared/ui/dropdown/DropdownTrigger.tsx
  src/shared/ui/progressbar/ProgressBar.test.tsx
  src/shared/ui/progressbar/ProgressBar.tsx
  src/shared/ui/tab/Tab.tsx
  src/widgets/Header/ui/HeaderProfileDropdownMenu.tsx
  src/widgets/Header/ui/LanguageSwitcher.tsx
  src/widgets/Header/ui/MobileGNB.tsx
Labels: 🛠️ refactor

#139 Refactor/#137 rename project
  .github/workflows/deploy.yml
  .github/workflows/sync-to-personal.yml
  README.md
  public/robots.txt
  src/app/sitemap.ts
  src/entities/gathering-detail/ui/GatheringDetailLayout.tsx
  src/features/gathering/ui/fields/GatheringImageField.tsx
  src/features/review/ui/CreateReviewModal.tsx
  src/messages/en.json
  src/messages/ko.json
  src/shared/lib/hooks/index.ts
  src/shared/lib/hooks/useImageProcessingToast.ts
  src/shared/lib/hooks/useImageResizer.ts
  src/shared/lib/metadata.ts
  src/shared/ui/skeleton/Skeleton.test.tsx
  src/shared/ui/skeleton/Skeleton.tsx
Labels: 🛠️ refactor

#142 Refactor/#141 lcp
  .env.test
  GIT_HOOKS_GUIDE.md
  README.md
  jest.config.mjs
  jest.env.js
  next.config.ts
  package.json
  pnpm-lock.yaml
  public/file.svg
  public/globe.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/[locale]/gathering/page.tsx
  src/app/__tests__/apiError.test.tsx
  src/app/__tests__/apiGet.test.tsx
  src/app/__tests__/apiPost.test.tsx
  src/entities/gathering-detail/ui/GatheringDetailLayout.tsx
  src/entities/user/ui/ProfileSection.test.tsx
  src/features/gathering/ui/CreateGatheringButton.test.tsx
  src/features/gathering/ui/CreateGatheringButton.tsx
  src/features/gathering/ui/FilterSection.test.tsx
  src/features/gathering/ui/FilterSection.tsx
  src/features/gathering/ui/GatheringDetailButton.test.tsx
  src/features/gathering/ui/GatheringDetailButton.tsx
  src/features/gathering/ui/GatheringLikeButton.tsx
  src/features/gathering/ui/index.ts
  src/shared/lib/store/authStore.ts
  src/shared/lib/store/index.ts
  src/shared/ui/OptimizedImage/OptimizedImage.test.tsx
  src/shared/ui/ProfileImage/ProfileImage.test.tsx
  src/widgets/ContainerInformation/cap-profile.jpg
  src/widgets/Footer/model/.gitkeep
  src/widgets/Footer/ui/.gitkeep
  src/widgets/Gathering/ui/GatheringPageWrapper.tsx
  src/widgets/GatheringCard/model/.gitkeep
  src/widgets/GatheringCard/ui/GatheringCard.test.skip.tsx
  src/widgets/GatheringCard/ui/GatheringCard.tsx
  src/widgets/GatheringCard/ui/MyPageGatheringCard.test.skip.tsx
  src/widgets/GatheringList/model/.gitkeep
  src/widgets/GatheringList/ui/.gitkeep
  src/widgets/Header/model/.gitkeep
  src/widgets/ReviewList/model/.gitkeep
Labels: 🛠️ refactor

#143 deploy: moizayo deploy
  .env.test
  GIT_HOOKS_GUIDE.md
  README.md
  jest.config.mjs
  jest.env.js
  next.config.ts
  package.json
  pnpm-lock.yaml
  public/file.svg
  public/globe.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/[locale]/gathering/page.tsx
  src/app/__tests__/apiError.test.tsx
  src/app/__tests__/apiGet.test.tsx
  src/app/__tests__/apiPost.test.tsx
  src/entities/gathering-detail/ui/GatheringDetailLayout.tsx
  src/entities/user/ui/ProfileSection.test.tsx
  src/features/gathering/ui/CreateGatheringButton.test.tsx
  src/features/gathering/ui/CreateGatheringButton.tsx
  src/features/gathering/ui/FilterSection.test.tsx
  src/features/gathering/ui/FilterSection.tsx
  src/features/gathering/ui/GatheringDetailButton.test.tsx
  src/features/gathering/ui/GatheringDetailButton.tsx
  src/features/gathering/ui/GatheringLikeButton.tsx
  src/features/gathering/ui/index.ts
  src/shared/lib/store/authStore.ts
  src/shared/lib/store/index.ts
  src/shared/ui/OptimizedImage/OptimizedImage.test.tsx
  src/shared/ui/ProfileImage/ProfileImage.test.tsx
  src/widgets/ContainerInformation/cap-profile.jpg
  src/widgets/Footer/model/.gitkeep
  src/widgets/Footer/ui/.gitkeep
  src/widgets/Gathering/ui/GatheringPageWrapper.tsx
  src/widgets/GatheringCard/model/.gitkeep
  src/widgets/GatheringCard/ui/GatheringCard.test.skip.tsx
  src/widgets/GatheringCard/ui/GatheringCard.tsx
  src/widgets/GatheringCard/ui/MyPageGatheringCard.test.skip.tsx
  src/widgets/GatheringList/model/.gitkeep
  src/widgets/GatheringList/ui/.gitkeep
  src/widgets/Header/model/.gitkeep
  src/widgets/ReviewList/model/.gitkeep
Labels: 🚀 deploy

#146 deploy: moizayo deploy
  README.md
  src/entities/gathering/ui/fields/GatheringDateField.test.tsx
  src/entities/gathering/ui/fields/GatheringDateField.tsx
  src/entities/gathering/ui/fields/GatheringRegistrationEndField.test.tsx
  src/entities/gathering/ui/fields/GatheringRegistrationEndField.tsx
  src/features/filters/ui/DateFilter.tsx
Labels: 🚀 deploy

#152 Design/#150 gathering card long text
  README.md
  src/widgets/GatheringCard/ui/GatheringCard.tsx
  src/widgets/GatheringCard/ui/MyPageGatheringCard.tsx
Labels: 📝 docs, 🎨 design

#160 fix: 리뷰카드 시간 변경 / 불필요한 suspense 제거
  jest.setup.js
  src/app/[locale]/reviews/page.tsx
  src/widgets/ReviewList/ui/ReviewList.tsx
Labels: 🎨 design

#159 Chore/#158 vercel option
  README.md
  next.config.ts
Labels: 🎸 chore

#157 Test/#156 tests signin signup
  src/features/signin/model/signinSchema.test.ts
  src/features/signin/model/signinSchema.ts
  src/features/signin/ui/SigninForm.test.tsx
  src/features/signup/model/signupSchema.test.ts
  src/features/signup/model/signupSchema.ts
  src/features/signup/utils/formatSignupFormToPayload.test.ts
  src/features/signup/utils/formatSignupFormToPayload.ts
  src/shared/ui/AuthPageDecoration/AuthPageDecoration.test.tsx
  src/shared/ui/InputWithLabel/InputWithLabel.tsx
  src/shared/ui/input/Input.test.tsx
  src/widgets/Header/ui/HeaderLink.tsx
Labels: ✅ test

#164 Feat/#163 landingpage
  package.json
  pnpm-lock.yaml
  src/app/[locale]/landing/page.tsx
  src/entities/landing/ui/HeroCard.tsx
  src/entities/landing/ui/LandingReviewCard.tsx
  src/entities/landing/ui/StepCard.tsx
  src/features/landing/PushGatheringPageButton.tsx
  src/features/signin/ui/SigninForm.test.tsx
  src/features/signin/ui/SigninForm.tsx
  src/i18n/routing.ts
  src/messages/en.json
  src/messages/ko.json
  src/shared/config/routes.ts
  src/shared/ui/FadeIn/index.tsx
  src/shared/ui/Pill/Pill.tsx
  src/shared/ui/Pill/index.ts
  src/shared/ui/background/GradientBG.tsx
  src/shared/ui/icon/icons/LandingCalendarIcon.tsx
  src/shared/ui/icon/icons/LandingHeartIcon.tsx
  src/shared/ui/icon/icons/LandingUsersIcon.tsx
  src/shared/ui/icon/icons/LeafIcon.tsx
  src/shared/ui/icon/icons/SparkleIcon.tsx
  src/widgets/Header/ui/Header.tsx
  src/widgets/Header/ui/Logo.tsx
  src/widgets/landing/ui/CTABanner.tsx
  src/widgets/landing/ui/FAQ.tsx
  src/widgets/landing/ui/FeaturesGrid.tsx
  src/widgets/landing/ui/HealingLanding.tsx
  src/widgets/landing/ui/Hero.tsx
  src/widgets/landing/ui/HowItWorks.tsx
  src/widgets/landing/ui/LandingFooter.tsx
  src/widgets/landing/ui/Stats.tsx
  src/widgets/landing/ui/Testimonials.tsx
Labels: ✨ feature

#165 Deploy: moizayo deploy
  README.md
  package.json
  pnpm-lock.yaml
  src/app/[locale]/landing/page.tsx
  src/entities/landing/ui/HeroCard.tsx
  src/entities/landing/ui/LandingReviewCard.tsx
  src/entities/landing/ui/StepCard.tsx
  src/features/landing/PushGatheringPageButton.tsx
  src/features/signin/ui/SigninForm.test.tsx
  src/features/signin/ui/SigninForm.tsx
  src/i18n/routing.ts
  src/messages/en.json
  src/messages/ko.json
  src/shared/config/routes.ts
  src/shared/ui/FadeIn/index.tsx
  src/shared/ui/Pill/Pill.tsx
  src/shared/ui/Pill/index.ts
  src/shared/ui/background/GradientBG.tsx
  src/shared/ui/icon/icons/LandingCalendarIcon.tsx
  src/shared/ui/icon/icons/LandingHeartIcon.tsx
  src/shared/ui/icon/icons/LandingUsersIcon.tsx
  src/shared/ui/icon/icons/LeafIcon.tsx
  src/shared/ui/icon/icons/SparkleIcon.tsx
  src/widgets/Header/ui/Header.tsx
  src/widgets/Header/ui/Logo.tsx
  src/widgets/landing/ui/CTABanner.tsx
  src/widgets/landing/ui/FAQ.tsx
  src/widgets/landing/ui/FeaturesGrid.tsx
  src/widgets/landing/ui/HealingLanding.tsx
  src/widgets/landing/ui/Hero.tsx
  src/widgets/landing/ui/HowItWorks.tsx
  src/widgets/landing/ui/LandingFooter.tsx
  src/widgets/landing/ui/Stats.tsx
  src/widgets/landing/ui/Testimonials.tsx
Labels: 🚀 deploy
