Repository FESI-10th-team6/moizayo, pull requests merged in 2025-07, with the labels that each got.

#8 Design/#6 Design token
  designTokens.json
  package.json
  pnpm-lock.yaml
  src/app/_variables.css
  src/app/globals.css
  style-dictionary.config.json
Labels: 🎨 design

#22 Design/14 공통 컴포넌트 작업 chip
  package.json
  pnpm-lock.yaml
  src/shared/ui/chip/chip.stories.tsx
  src/shared/ui/chip/chip.tsx
  src/shared/ui/chip/index.ts
  src/shared/ui/chip/infoChip.stories.tsx
  src/shared/ui/chip/infoChip.tsx
  src/shared/ui/chip/stateChip.stories.tsx
  src/shared/ui/chip/stateChip.tsx
  src/shared/ui/chip/timeChip.stories.tsx
  src/shared/ui/chip/timeChip.tsx
Labels: 🎨 design

#28 Design/#10 공통 컴포넌트 input
  src/shared/ui/input/Input.stories.tsx
  src/shared/ui/input/Input.test.tsx
  src/shared/ui/input/Input.tsx
  src/shared/ui/input/index.ts
Labels: 🎨 design

#34 Design/24 공통 컴포넌트 작업 드롭다운
  src/shared/ui/chip/Chip.stories.tsx
  src/shared/ui/chip/Chip.tsx
  src/shared/ui/chip/InfoChip.stories.tsx
  src/shared/ui/chip/InfoChip.tsx
  src/shared/ui/chip/StateChip.stories.tsx
  src/shared/ui/chip/StateChip.tsx
  src/shared/ui/chip/TimeChip.stories.tsx
  src/shared/ui/chip/TimeChip.tsx
  src/shared/ui/chip/index.ts
  src/shared/ui/dropdown/Dropdown.stories.tsx
  src/shared/ui/dropdown/Dropdown.test.tsx
  src/shared/ui/dropdown/Dropdown.tsx
  src/shared/ui/dropdown/DropdownItem.tsx
  src/shared/ui/dropdown/DropdownList.tsx
  src/shared/ui/dropdown/DropdownTrigger.tsx
  src/shared/ui/dropdown/dropdown-variants.ts
  src/shared/ui/dropdown/index.ts
Labels: 🎨 design

#43 feat: BottomFloatingBar 구현 및 테스트 코드 작성
  src/widgets/BottomFloatingBar/BottomFloatingBar.stories.tsx
  src/widgets/BottomFloatingBar/BottomFloatingBar.test.tsx
  src/widgets/BottomFloatingBar/BottomFloatingBar.tsx
Labels: 🎨 design

#46 Design/#31 공통 컴포넌트 작업 모달
  src/shared/ui/button/Button.tsx
  src/shared/ui/modal/BasicModal.stories.tsx
  src/shared/ui/modal/BasicModal.test.tsx
  src/shared/ui/modal/BasicModal.tsx
  src/shared/ui/modal/ModalBase.tsx
  src/shared/ui/modal/ModalLayout.tsx
  src/shared/ui/modal/Popup.stories.tsx
  src/shared/ui/modal/Popup.test.tsx
  src/shared/ui/modal/Popup.tsx
  src/shared/ui/modal/index.ts
  src/shared/ui/modal/variants.ts
  src/shared/ui/pagination/Pagination.stories.tsx
Labels: 🎨 design

#51 Design/#44 container information
  src/shared/ui/chip/InfoChip.stories.tsx
  src/shared/ui/chip/InfoChip.tsx
  src/widgets/ContainerInformation/AvatarGroup.tsx
  src/widgets/ContainerInformation/ContainerInformation.stories.tsx
  src/widgets/ContainerInformation/ContainerInformation.test.tsx
  src/widgets/ContainerInformation/ContainerInformation.tsx
  src/widgets/ContainerInformation/cap-profile.jpg
Labels: 🎨 design

#63 hotfix: yml 문법 수정
  .github/workflows/deploy.yml
Labels: 🚀 deploy

#65 Feat/#55 page review
  next.config.ts
  src/app/[locale]/reviews/page.tsx
  src/app/messages/en.json
  src/app/messages/ko.json
  src/entities/review/api/reviewApi.ts
  src/entities/review/model/type.ts
  src/entities/review/ui/ReviewCard.stories.tsx
  src/entities/review/ui/ReviewCard.tsx
  src/features/review/ReviewListFilter/ui/ReviewListFilter.tsx
  src/features/review/ReviewSort/ui/ReviewSort.tsx
  src/features/review/ReviewTypeFilter/ui/ReviewTypeFilter.tsx
  src/features/review/model/.gitkeep
  src/features/review/ui/.gitkeep
  src/shared/lib/dateFormatter.ts
  src/shared/ui/filter/Filter.tsx
  src/shared/ui/icon/icons/StarIcon.tsx
  src/shared/ui/pageInfoLayout/PageInfoLayout.tsx
  src/shared/ui/pageInfoLayout/index.ts
  src/widgets/AllReviewRating/constants.ts
  src/widgets/AllReviewRating/index.ts
  src/widgets/AllReviewRating/ui/AllReviewRating.tsx
  src/widgets/AllReviewRating/ui/RatingScore.tsx
  src/widgets/AllReviewRating/ui/RatingScoreProgressBar.tsx
  src/widgets/ReviewList/ui/ReviewList.tsx
Labels: ✨ feature

#67 Feat/#64 gatherign list page
  src/app/[locale]/gathering/page.tsx
  src/app/messages/en.json
  src/app/messages/ko.json
  src/entities/gathering/api/queries.ts
  src/entities/gathering/api/services.ts
  src/entities/gathering/model/filters.ts
  src/entities/gathering/model/types.ts
  src/features/gathering/ui/DateFilter.tsx
  src/features/gathering/ui/FilterSection.tsx
  src/features/gathering/ui/GatheringJoinButton.tsx
  src/features/gathering/ui/GatheringLikeButton.tsx
  src/features/gathering/ui/index.ts
  src/shared/api/httpClient.ts
  src/shared/config/routes.ts
  src/shared/ui/calendar/Calendar.tsx
  src/shared/ui/icon/icons/DalaemfitIcon.tsx
  src/shared/ui/icon/icons/WorkationIcon.tsx
  src/shared/ui/tab/Tab.tsx
  src/widgets/GatheringCard/ui/GatheringCard.test.skip.tsx
  src/widgets/GatheringCard/ui/GatheringCard.tsx
  src/widgets/GatheringCard/ui/MyPageGatheringCard.test.skip.tsx
Labels: ✨ feature

#74 Feat/#52 page gathering detail
  src/app/[locale]/gathering/[id]/page.tsx
  src/entities/gathering-detail/api/queries.ts
  src/entities/gathering-detail/api/services.ts
  src/entities/gathering-detail/model/types.ts
  src/entities/gathering-detail/ui/GatheringDetailLayout.tsx
  src/entities/gathering-detail/ui/ReviewList.tsx
  src/entities/gathering-detail/ui/index.ts
  src/entities/participant/api/queries.ts
  src/entities/participant/api/queryKeys.ts
  src/entities/participant/api/services.ts
  src/entities/participant/model/types.ts
  src/entities/review/api/reviewApi.ts
  src/entities/review/hooks/useGatheringReviewList.ts
  src/shared/lib/date/formatDateAndTime.ts
  src/shared/lib/date/index.ts
  src/shared/ui/tag/index.ts
  src/widgets/BottomFloatingBar/BottomFloatingBar.tsx
  src/widgets/BottomFloatingBar/index.ts
  src/widgets/ContainerInformation/AvatarGroup.tsx
  src/widgets/ContainerInformation/ContainerInformation.stories.tsx
  src/widgets/ContainerInformation/ContainerInformation.test.tsx
  src/widgets/ContainerInformation/ContainerInformation.tsx
  src/widgets/ContainerInformation/index.ts
Labels: ✨ feature

#73 Feat/#47 signup
  src/app/[locale]/(auth)/layout.tsx
  src/app/[locale]/(auth)/signup/page.tsx
  src/app/_variables.css
  src/app/messages/en.json
  src/app/messages/ko.json
  src/entities/auth/signup/api/signup.ts
  src/features/auth/model/.gitkeep
  src/features/auth/ui/.gitkeep
  src/features/login/model/loginFields.ts
  src/features/signup/model/signupFields.ts
  src/features/signup/model/signupSchema.ts
  src/features/signup/model/type.ts
  src/features/signup/ui/SignupForm.tsx
  src/features/signup/utils/formatSignupFormToPayload.ts
  src/shared/hooks/useAuthImageSize.ts
  src/shared/lib/getAuthImageSize.ts
  src/shared/lib/getBreakpointsPx.test.ts
  src/shared/lib/getBreakpointsPx.ts
  src/shared/lib/localeUrlFormatter.ts
  src/shared/ui/AuthPageDecoration/AuthPageDecoration.tsx
  src/shared/ui/InputWithLabel/InputWithLabel.tsx
  src/shared/ui/InputWithLabel/index.ts
  src/shared/ui/icon/icons/LoginImageIcon.tsx
  src/shared/ui/input/Input.stories.tsx
  src/shared/ui/input/Input.test.tsx
  src/shared/ui/input/Input.tsx
  src/widgets/AuthForm/model/types.ts
  src/widgets/AuthForm/ui/AuthForm.tsx
  src/widgets/Header/ui/Header.tsx
  src/widgets/Header/ui/HeaderLink.tsx
  src/widgets/Header/ui/MobileGNB.tsx
Labels: ✨ feature

#76 Design/#72 feat mobile menu size
  src/app/[locale]/layout.tsx
  src/widgets/Header/ui/Header.tsx
  src/widgets/Header/ui/MobileGNB.tsx
Labels: 🎨 design

#80 Feat/#78 create gathering api
  middleware.ts
  next.config.ts
  src/app/[locale]/(auth)/signin/page.tsx
  src/app/[locale]/gathering/[id]/page.tsx
  src/app/[locale]/gathering/page.tsx
  src/app/[locale]/layout.tsx
  src/app/[locale]/my-page/page.tsx
  src/app/[locale]/page.tsx
  src/app/[locale]/reviews/page.tsx
  src/app/page.tsx
  src/entities/gathering/api/README.md
  src/entities/gathering/api/index.ts
  src/entities/gathering/api/queries.ts
  src/entities/gathering/api/services.ts
  src/features/gathering/ui/CreateGatheringForm.tsx
  src/features/gathering/ui/CreateGatheringModal.tsx
  src/features/gathering/ui/DateFilter.tsx
  src/features/gathering/ui/FilterSection.tsx
  src/features/gathering/ui/fields/GatheringLocationField.tsx
  src/features/gathering/ui/fields/index.ts
  src/features/review/ReviewListFilter/ui/ReviewListFilter.tsx
  src/features/review/ReviewSort/ui/ReviewSort.tsx
  src/features/review/ReviewTypeFilter/ui/ReviewTypeFilter.tsx
  src/features/signup/model/index.ts
  src/features/signup/ui/SignupForm.tsx
  src/i18n.ts
  src/i18n/index.ts
  src/i18n/navigation.ts
  src/i18n/request.ts
  src/i18n/routing.ts
  src/messages/en.json
  src/messages/ko.json
  src/shared/lib/localeUrlFormatter.ts
  src/shared/ui/time-picker/TimePicker.tsx
  src/widgets/AuthForm/model/types.ts
  src/widgets/GatheringCard/ui/GatheringCard.tsx
  src/widgets/Header/ui/Header.tsx
  src/widgets/Header/ui/HeaderLink.tsx
  src/widgets/Header/ui/LanguageSwitcher.tsx
  src/widgets/Header/ui/Logo.tsx
  src/widgets/Header/ui/MobileGNB.tsx
Labels: ✨ feature

#88 Feat/#86 gathering list ui ux
  src/entities/gathering/api/services.ts
  src/entities/gathering/ui/GatheringDateTimeDisplay.tsx
  src/entities/gathering/ui/GatheringDeadlineTag.tsx
  src/entities/gathering/ui/GatheringStatusChip.tsx
  src/entities/review/api/my-page.ts
  src/entities/user/api/service.ts
  src/entities/user/model/schema.ts
  src/entities/user/ui/ProfileEditForm.tsx
  src/entities/user/ui/ProfileSection.tsx
  src/features/gathering/ui/GatheringJoinButton.tsx
  src/features/review/ui/CreateReviewModal.tsx
  src/messages/en.json
  src/messages/ko.json
  src/widgets/GatheringCard/ui/GatheringCard.tsx
Labels: ✨ feature

#93 fix: 한영 변환 새로고침 오류 해결
  src/app/[locale]/favorites/page.tsx
  src/entities/favorites/api/queries.ts
  src/entities/favorites/api/queryKeys.ts
  src/entities/favorites/ui/FavoritesList.tsx
  src/features/filters/ui/DateFilter.tsx
  src/messages/en.json
  src/messages/ko.json
  src/widgets/FavoritesSkeleton/index.ts
  src/widgets/FavoritesSkeleton/ui/FavoritesSkeletonCard.tsx
  src/widgets/FavoritesSkeleton/ui/FavoritesSkeletonList.tsx
Labels: 🐞 fix

#90 Feat/#71 page signin
  next-auth.d.ts
  src/app/[locale]/page.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/page.tsx
  src/entities/auth/model/types.ts
  src/entities/user/ui/ProfileSection.tsx
  src/features/signin/ui/SigninForm.tsx
  src/messages/en.json
  src/messages/ko.json
  src/shared/api/httpClient.ts
  src/shared/ui/AuthPageDecoration/AuthPageDecoration.tsx
  src/shared/ui/ProfileImage/ProfileImage.tsx
  src/shared/ui/ProfileImage/index.ts
  src/shared/ui/button/Button.tsx
  src/shared/ui/button/button.test.tsx
  src/shared/ui/dropdown/Dropdown.tsx
  src/shared/ui/dropdown/DropdownList.tsx
  src/shared/ui/input/Input.tsx
  src/widgets/AuthForm/ui/AuthForm.tsx
  src/widgets/Header/ui/Header.tsx
  src/widgets/Header/ui/HeaderProfileDropdownMenu.tsx
  src/widgets/Header/ui/LanguageSwitcher.tsx
  src/widgets/Header/ui/MobileGNB.tsx
Labels: ✨ feature

#103 Chore/#98 env environment
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  next.config.ts
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/gathering-default-image.png
  src/app/api/auth/[...nextauth]/route.ts
  src/app/layout.tsx
  src/entities/gathering-detail/api/queries.ts
  src/entities/gathering-detail/api/services.ts
  src/entities/gathering-detail/ui/GatheringDetailLayout.tsx
  src/entities/gathering/api/services.ts
  src/entities/gathering/model/filters.ts
  src/entities/review/api/my-page.ts
  src/entities/review/ui/ReviewCard.tsx
  src/entities/user/ui/ProfileSection.tsx
  src/features/gathering/ui/CreateGatheringButton.tsx
  src/features/my-page/ui/GatheringsCreatedContent.tsx
  src/features/my-page/ui/GatheringsJoinedContent.tsx
  src/features/my-page/ui/MyPageActionButton.tsx
  src/features/my-page/ui/MyPageTab.tsx
  src/features/my-page/ui/ReviewsContent.tsx
  src/features/review/ui/CreateReviewModal.tsx
  src/i18n/request.ts
  src/messages/en.json
  src/messages/ko.json
  src/shared/api/httpClient.ts
  src/shared/api/logger.ts
  src/shared/config/api.ts
  src/shared/ui/modal/ModalLayout.tsx
  src/widgets/GatheringCard/ui/GatheringCard.stories.tsx
  src/widgets/GatheringCard/ui/GatheringCard.test.skip.tsx
  src/widgets/GatheringCard/ui/GatheringCard.tsx
  src/widgets/GatheringCard/ui/MyPageGatheringCard.stories.tsx
  src/widgets/GatheringCard/ui/MyPageGatheringCard.test.skip.tsx
  src/widgets/GatheringCard/ui/MyPageGatheringCard.tsx
  src/widgets/Header/ui/LanguageSwitcher.tsx
Labels: ✨ feature, 🎸 chore
